#%RAML 1.0 NamedExample
value:
    ACCT_NO: '300007000855'
    ACCT_TYPE: 'L'
    BRANCH: '501'
    STAFF_CODE: 'BA9'
    STATUS: '2'
    CURRENCY_CD: 'THB'
    CUR_BALANCE: 500000.00
    RELEASE_DATE: 2006-02-21
    EXPIRE_DATE: 2010-01-27