#%RAML 1.0 NamedExample
value:
-
  CARD_TYPE_NO: '0001'
  TYPE_DESC: 'Gold'
  ANNUAL_FEE: 500.00
  EXPIRE_DATE: 2018-12-31
-
  CARD_TYPE_NO: '0002'
  TYPE_DESC: 'Silver'
  ANNUAL_FEE: 200.00
  EXPIRE_DATE: 2019-01-31
-
  CARD_TYPE_NO: '0003'
  TYPE_DESC: 'Platinum'
  ANNUAL_FEE: 100.00
  EXPIRE_DATE: 2020-01-31