#%RAML 1.0 NamedExample
value:
-
  ACCOUNT_NO: '0300007000855'
  CUST_NO: '0001'
  CARD_NAME: 'Monday Jun'
  CARD_TYPE: '0001'
  CARD_STATUS: '1'
  CVC: '123'
  EXPIRE_DATE: 2018-12-31
-
  ACCOUNT_NO: '0300007000855'
  CUST_NO: '0001'
  CARD_NAME: 'Monday Jun'
  CARD_TYPE: '0002'
  CARD_STATUS: '1'
  CVC: '123'
  EXPIRE_DATE: 2019-12-31
-
  ACCOUNT_NO: '0300007000855'
  CUST_NO: '0001'
  CARD_NAME: 'Monday Jun'
  CARD_TYPE: '0003'
  CARD_STATUS: '1'
  CVC: '123'
  EXPIRE_DATE: 2020-12-31
-
  ACCOUNT_NO: '14017010500'
  CUST_NO: '0002'
  CARD_NAME: 'Tuesday Aungkarn'
  CARD_TYPE: '0003'
  CARD_STATUS: '1'
  CVC: '123'
  EXPIRE_DATE: 2021-12-31