#%RAML 1.0 NamedExample
value:
-
  CUST_NO: '00001'
  ID_NO: '1111122222333'
  NAME: 'Monday'
  LASTNAME: 'Jun'
  DOB: 1979-06-15
  REG_DATE: 2010-01-27
  REMARK: ''
-
  CUST_NO: '00002'
  ID_NO: '1111133333222'
  NAME: 'Tuesday'
  LASTNAME: 'Aungkarn'
  DOB: 1964-03-01
  REG_DATE: 2007-06-26
  REMARK: ''
-
  CUST_NO: '00003'
  ID_NO: '2222211111333'
  NAME: 'Wednesday'
  LASTNAME: 'Pud'
  DOB: 1987-07-02
  REG_DATE: 2006-04-28
  REMARK: ''
-
  CUST_NO: '00004'
  ID_NO: '2222233333111'
  NAME: 'Thursday'
  LASTNAME: 'Paruhud'
  DOB: 1971-06-27
  REG_DATE: 2006-05-02
  REMARK: ''
-
  CUST_NO: '00005'
  ID_NO: '3333322222111'
  NAME: 'Friday'
  LASTNAME: 'Sook'
  DOB: 1965-10-09
  REG_DATE: 2017-11-06
  REMARK: ''
-
  CUST_NO: '00006'
  ID_NO: '3333311111222'
  NAME: 'Saturday'
  LASTNAME: 'Sao'
  DOB: 1974-09-07
  REG_DATE: 2018-02-22
  REMARK: ''